default: &default
  adapter: postgresql
  encoding: utf-8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('JOINTHUB_DATABASE_USER') { 'jointhub' }%>
  password: <%= ENV.fetch('JOINTHUB_DATABASE_PASSWORD') { 'password' }%>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>

development:
  <<: *default
  database: jointhub_development

test:
  <<: *default
  database: jointhub_test