default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['JOINTHUB_DATABASE_USER'] %>
  password: <%= ENV['JOINTHUB_DATABASE_PASSWORD'] %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>

development:
  <<: *default
  database: jointhub_development

test:
  <<: *default
  database: jointhub_test

production:
  <<: *default
  database: jointhub_production